# Generated by Django 3.1.3 on 2021-05-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210530_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='code_postale',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='state',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='street',
        ),
        migrations.AddField(
            model_name='reviews',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reviews',
            name='code_postale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reviews',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reviews',
            name='street',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
