# Generated by Django 3.1.3 on 2021-05-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210530_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
